SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_OUTS O
JOIN ANIMAL_INS I ON O.ANIMAL_ID = I.ANIMAL_ID
# DATEDIFF() 힘수 SELECT 뿐만 아니라 WHERE, ORDER BY 등등 다 됨
ORDER BY DATEDIFF(O.DATETIME, I.DATETIME) DESC
LIMIT 2;