SELECT YEAR(SALES_DATE) AS YEAR, 
    MONTH(SALES_DATE) AS MONTH, 
    GENDER, 
    # 한 사람이 같은 년도, 같은 월에 여러 번 구매한 경우를 생각해야함. 그래도 1로 계산. 그러므로 DISTINCT 
    COUNT(DISTINCT U.USER_ID) AS USERS
FROM USER_INFO U
JOIN ONLINE_SALE O ON U.USER_ID = O.USER_ID
WHERE U.GENDER IS NOT NULL
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY YEAR ASC, MONTH ASC, GENDER ASC;