SELECT CAR_ID, 
    # DATEDIFF는 두 날짜 사이의 간격을 계산하지, 날짜의 개수를 세어주지 않기에 +1 해야함.
       ROUND(AVG(DATEDIFF(END_DATE, START_DATE) + 1), 1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
# 평균 대여 기간이 7일 이상이어야 하기에 HAVING으로 조건 걸어야 함.
HAVING ROUND(AVG(DATEDIFF(END_DATE, START_DATE) + 1), 1) >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;