SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO I
JOIN ITEM_TREE T ON I.ITEM_ID = T.ITEM_ID
WHERE T.PARENT_ITEM_ID IN (  # RARE들의 자식들을 찾음
    SELECT ITEM_ID 
    FROM ITEM_INFO
    WHERE RARITY = 'RARE'  # (0, 1, 3, 4) 먼저 희귀도 RARE을 찾고
)
ORDER BY I.ITEM_ID DESC;